const temp1 = [
  'pumped',
  'ror',
  'offshore',
  'onshore',
  'solar',
  'coal',
  'lng',
  'oil',
  'diesel',
  'co_gen',
  'fission',
]
const temp2 = [
  'keelung_city',
  'new_taipei_city',
  'taipei_city',
  'taoyuan_city',
  'hsinchu_city',
  'hsinchu_county',
  'miaoli_county',
  'nantou_county',
  'taichung_city',
  'changhua_county',
  'yunlin_county',
  'chiayi_county',
  'chiayi_city',
  'tainan_city',
  'kaohsiung_city',
  'pingtung_county',
  'penghu_county',
  'yilan_county',
  'hualien_county',
  'taitung_county',
  'kinmen_county',
  'lienchiang_county',
]
export default [
  {
    name: '第一核能發電廠',
    energy: 'fission',
    county: 'new_taipei_city',
  },
  {
    name: '第三核能發電廠',
    energy: 'fission',
    county: 'pingtung_county',
  },
  {
    name: '林口發電廠',
    energy: 'coal',
    county: 'new_taipei_city',
  },
  {
    name: '台中發電廠',
    energy: 'coal',
    county: 'taichung_city',
  },
  {
    name: '和平電廠',
    energy: 'coal',
    county: 'hualien_county',
  },
  {
    name: '麥寮發電廠',
    energy: 'coal',
    county: 'yunlin_county',
  },
  {
    name: '海湖發電廠',
    energy: 'lng',
    county: 'taoyuan_city',
  },
  {
    name: '新桃電廠',
    energy: 'lng',
    county: 'hsinchu_county',
  },
  {
    name: '通霄發電廠',
    energy: 'lng',
    county: 'miaoli_county',
  },
  {
    name: '星元電廠',
    energy: 'lng',
    county: 'changhua_county',
  },
  {
    name: '嘉惠電廠 ',
    energy: 'lng',
    county: 'chiayi_county',
  },
  {
    name: '森霸電廠',
    energy: 'lng',
    county: 'tainan_city',
  },
  {
    name: '南部發電廠',
    energy: 'lng',
    county: 'kaohsiung_city',
  },
  {
    name: '協和發電廠',
    energy: 'oil',
    county: 'keelung_city',
  },
  {
    name: '尖山發電廠',
    energy: 'diesel',
    county: 'penghu_county',
  },
  {
    name: '塔山發電廠',
    energy: 'diesel',
    county: 'kinmen_county',
  },
  {
    name: '綠島發電廠',
    energy: 'diesel',
    county: 'taitung_county',
  },
  {
    name: '東引發電廠',
    energy: 'diesel',
    county: 'lienchiang_county',
  },
  {
    name: '興達發電廠',
    energy: 'coal',
    county: 'kaohsiung_city',
  },
  {
    name: '烏來發電廠',
    energy: 'ror',
    county: 'new_taipei_city',
  },
  {
    name: '石門發電廠',
    energy: 'ror',
    county: 'taoyuan_city',
  },
  {
    name: '軟橋發電廠',
    energy: 'ror',
    county: 'hsinchu_county',
  },
  {
    name: '卓蘭發電廠',
    energy: 'ror',
    county: 'miaoli_county',
  },
  {
    name: '德基發電廠',
    energy: 'ror',
    county: 'taichung_city',
  },
  {
    name: '萬大發電廠',
    energy: 'ror',
    county: 'nantou_county',
  },
  {
    name: '烏山頭水力發電廠',
    energy: 'ror',
    county: 'tainan_city',
  },
  {
    name: '竹子門發電廠',
    energy: 'ror',
    county: 'kaohsiung_city',
  },
  {
    name: '天送埤發電廠',
    energy: 'ror',
    county: 'yilan_county',
  },
  {
    name: '碧海發電廠',
    energy: 'ror',
    county: 'hualien_county',
  },
  {
    name: '卑南上圳小型發電廠',
    energy: 'ror',
    county: 'taitung_county',
  },
  {
    name: '明湖抽蓄水力發電廠',
    energy: 'pumped',
    county: 'nantou_county',
  },
  {
    name: '石門風力發電站',
    energy: 'onshore',
    county: 'new_taipei_city',
  },
  {
    name: '觀園風力發電站',
    energy: 'onshore',
    county: 'taoyuan_city',
  },
  {
    name: '香山風力發電站',
    energy: 'onshore',
    county: 'hsinchu_city',
  },
  {
    name: '臺中港風力發電站',
    energy: 'onshore',
    county: 'taichung_city',
  },
  {
    name: '彰工風力發電站',
    energy: 'onshore',
    county: 'changhua_county',
  },
  {
    name: '雲麥風力發電站',
    energy: 'onshore',
    county: 'yunlin_county',
  },
  {
    name: '恆春風力發電站',
    energy: 'onshore',
    county: 'pingtung_county',
  },
  {
    name: '中屯風力發電站',
    energy: 'onshore',
    county: 'penghu_county',
  },
  {
    name: '金沙風力發電站',
    energy: 'onshore',
    county: 'kinmen_county',
  },
  {
    name: '苗栗竹南風力發電站',
    energy: 'onshore',
    county: 'miaoli_county',
  },
  {
    name: '豐威風力發電站',
    energy: 'onshore',
    county: 'hsinchu_county',
  },
  {
    name: '海洋竹南風力發電場',
    energy: 'offshore',
    county: 'miaoli_county',
  },
]
